# Generated by Django 2.2.4 on 2021-09-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210925_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
